spring.application.name=ms-comp-prueba-Diego-Bedoya
server.port=8090
spring.datasource.url=jdbc:postgresql://localhost:5432/cafeteria
spring.datasource.username=postgres
spring.datasource.password=hola1234
